# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Sun Oct 13 14:46:52 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.local_refresh_button = QtWidgets.QPushButton(self.tab)
        self.local_refresh_button.setGeometry(QtCore.QRect(700, 480, 80, 26))
        self.local_refresh_button.setObjectName("local_refresh_button")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(9, 29, 681, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 679, 479))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_widget_contents.sizePolicy().hasHeightForWidth())
        self.scroll_area_widget_contents.setSizePolicy(sizePolicy)
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.device_info_label = QtWidgets.QLabel(self.scroll_area_widget_contents)
        self.device_info_label.setGeometry(QtCore.QRect(10, 0, 661, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_info_label.sizePolicy().hasHeightForWidth())
        self.device_info_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.device_info_label.setFont(font)
        self.device_info_label.setText("")
        self.device_info_label.setObjectName("device_info_label")
        self.device_tip_label = QtWidgets.QLabel(self.scroll_area_widget_contents)
        self.device_tip_label.setGeometry(QtCore.QRect(0, -1, 681, 481))
        self.device_tip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.device_tip_label.setObjectName("device_tip_label")
        self.scrollArea.setWidget(self.scroll_area_widget_contents)
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 781, 27))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.sniffer_start_button = QtWidgets.QPushButton(self.tab_2)
        self.sniffer_start_button.setGeometry(QtCore.QRect(700, 480, 80, 26))
        self.sniffer_start_button.setObjectName("sniffer_start_button")
        self.sniffer_stop_button = QtWidgets.QPushButton(self.tab_2)
        self.sniffer_stop_button.setGeometry(QtCore.QRect(700, 450, 80, 26))
        self.sniffer_stop_button.setObjectName("sniffer_stop_button")
        self.sniffer_table = QtWidgets.QTableView(self.tab_2)
        self.sniffer_table.setGeometry(QtCore.QRect(5, 31, 691, 481))
        self.sniffer_table.setObjectName("sniffer_table")
        self.sniffer_tip_label = QtWidgets.QLabel(self.tab_2)
        self.sniffer_tip_label.setGeometry(QtCore.QRect(13, 37, 681, 471))
        self.sniffer_tip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sniffer_tip_label.setObjectName("sniffer_tip_label")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 781, 27))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.scan_result_table = QtWidgets.QTableView(self.tab_3)
        self.scan_result_table.setGeometry(QtCore.QRect(5, 80, 771, 431))
        self.scan_result_table.setObjectName("scan_result_table")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 761, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(71, 0))
        self.label_4.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.scan_target_ip_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_target_ip_edit.sizePolicy().hasHeightForWidth())
        self.scan_target_ip_edit.setSizePolicy(sizePolicy)
        self.scan_target_ip_edit.setMinimumSize(QtCore.QSize(160, 0))
        self.scan_target_ip_edit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.scan_target_ip_edit.setObjectName("scan_target_ip_edit")
        self.horizontalLayout_4.addWidget(self.scan_target_ip_edit)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(71, 0))
        self.label_5.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.scan_timeout_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_timeout_edit.sizePolicy().hasHeightForWidth())
        self.scan_timeout_edit.setSizePolicy(sizePolicy)
        self.scan_timeout_edit.setMinimumSize(QtCore.QSize(31, 0))
        self.scan_timeout_edit.setMaximumSize(QtCore.QSize(31, 16777215))
        self.scan_timeout_edit.setObjectName("scan_timeout_edit")
        self.horizontalLayout_4.addWidget(self.scan_timeout_edit)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(61, 0))
        self.label_6.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.scan_start_port_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_start_port_edit.sizePolicy().hasHeightForWidth())
        self.scan_start_port_edit.setSizePolicy(sizePolicy)
        self.scan_start_port_edit.setMinimumSize(QtCore.QSize(51, 0))
        self.scan_start_port_edit.setMaximumSize(QtCore.QSize(51, 16777215))
        self.scan_start_port_edit.setObjectName("scan_start_port_edit")
        self.horizontalLayout_4.addWidget(self.scan_start_port_edit)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(13, 0))
        self.label_7.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.scan_stop_port_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_stop_port_edit.sizePolicy().hasHeightForWidth())
        self.scan_stop_port_edit.setSizePolicy(sizePolicy)
        self.scan_stop_port_edit.setMinimumSize(QtCore.QSize(51, 0))
        self.scan_stop_port_edit.setMaximumSize(QtCore.QSize(51, 16777215))
        self.scan_stop_port_edit.setObjectName("scan_stop_port_edit")
        self.horizontalLayout_4.addWidget(self.scan_stop_port_edit)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.scan_stop_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.scan_stop_button.setMinimumSize(QtCore.QSize(80, 0))
        self.scan_stop_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.scan_stop_button.setObjectName("scan_stop_button")
        self.horizontalLayout_4.addWidget(self.scan_stop_button)
        self.scan_start_button = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_start_button.sizePolicy().hasHeightForWidth())
        self.scan_start_button.setSizePolicy(sizePolicy)
        self.scan_start_button.setMinimumSize(QtCore.QSize(80, 0))
        self.scan_start_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.scan_start_button.setObjectName("scan_start_button")
        self.horizontalLayout_4.addWidget(self.scan_start_button)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.actionGfdsg = QtWidgets.QAction(MainWindow)
        self.actionGfdsg.setObjectName("actionGfdsg")
        self.menu.addAction(self.action_about)
        self.menu.addAction(self.action_close)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_close, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Net Listener 网络嗅探工具", None, -1))
        self.local_refresh_button.setText(QtWidgets.QApplication.translate("MainWindow", "检测", None, -1))
        self.device_tip_label.setText(QtWidgets.QApplication.translate("MainWindow", "点击检测按钮开始检测。", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "本地网络信息", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "本地网络信息", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "局域网嗅探", None, -1))
        self.sniffer_start_button.setText(QtWidgets.QApplication.translate("MainWindow", "开始嗅探", None, -1))
        self.sniffer_stop_button.setText(QtWidgets.QApplication.translate("MainWindow", "停止", None, -1))
        self.sniffer_tip_label.setText(QtWidgets.QApplication.translate("MainWindow", "点击右下方按钮开始或停止嗅探", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "局域网嗅探", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "端口扫描", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "目标主机IP：", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "超时时间(s)：", None, -1))
        self.scan_timeout_edit.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "端口范围：", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.scan_stop_button.setText(QtWidgets.QApplication.translate("MainWindow", "停止", None, -1))
        self.scan_start_button.setText(QtWidgets.QApplication.translate("MainWindow", "扫描", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "端口扫描", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "操作", None, -1))
        self.action_close.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.action.setText(QtWidgets.QApplication.translate("MainWindow", "关于本软件", None, -1))
        self.action_about.setText(QtWidgets.QApplication.translate("MainWindow", "关于本软件", None, -1))
        self.actionGfdsg.setText(QtWidgets.QApplication.translate("MainWindow", "gfdsg", None, -1))

